name: Run tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Installing dependencies
        working-directory: ./src
        run: npm install --production=false
      - name: Running tests
        working-directory: ./src
        run: npm test
